services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
